<script>
/* ============================================================
   CROP KNOWLEDGE BASE
   sun: hours of direct sun needed (min)
   water: inches per week
   sp: in-row spacing (inches)   psf: plants per square foot
   depth: seed depth (inches)    germ: [minDays,maxDays]  soilF: [min,opt,max]
   dtm: days to maturity        from: "seed" | "transplant"
   via: seed viability (years)  feeder: heavy|medium|light
   start weeks are RELATIVE TO LAST SPRING FROST (negative = before)
     indoor: start indoors   tp: transplant out   direct: direct sow
     fall: weeks BEFORE first fall frost to sow a fall crop
   succ: succession interval in days (0 = not a succession crop)
   yield: typical lbs per plant per season
   ============================================================ */
const FAMILY = {
  solanaceae:{n:"Nightshade",c:"#c9453c"}, brassica:{n:"Brassica",c:"#5b8def"},
  cucurbit:{n:"Cucurbit",c:"#e8a33d"},     legume:{n:"Legume",c:"#3fae6b"},
  allium:{n:"Allium",c:"#9b6bd6"},         apiaceae:{n:"Umbellifer",c:"#e0705a"},
  chenopod:{n:"Chenopod",c:"#c94f8a"},     aster:{n:"Aster",c:"#f0a500"},
  poaceae:{n:"Grass",c:"#b0a13d"},         lamiaceae:{n:"Mint family",c:"#4bb3a5"},
  malvaceae:{n:"Mallow",c:"#8a6a4f"},      convolvulaceae:{n:"Morning glory",c:"#a05a9b"},
  rosaceae:{n:"Rose family",c:"#e05a7a"},  polygonaceae:{n:"Knotweed",c:"#7a8a5a"},
  asparagaceae:{n:"Asparagus",c:"#5ab08a"},tropaeolaceae:{n:"Nasturtium",c:"#e8743d"},
  boraginaceae:{n:"Borage",c:"#5a7ae0"}
};

const CROPS = [
/* ---------- NIGHTSHADES ---------- */
{id:"tomato",n:"Tomato",e:"🍅",fam:"solanaceae",sun:8,water:1.5,sp:24,psf:0.25,depth:0.25,germ:[5,10],soilF:[60,80,95],dtm:75,from:"transplant",via:5,feeder:"heavy",
 start:{indoor:-6,tp:2,fall:null},succ:0,yield:10,ph:"6.0–6.8",
 comp:["basil","marigold","borage","carrot","onion","parsley","nasturtium","chive","lettuce","asparagus"],
 foes:["cabbage","broccoli","cauliflower","kale","corn","fennel","potato","dill"],
 npk:"Low-N until first fruit set, then 5-10-10. Calcium matters — blossom end rot is a calcium-uptake problem, usually from uneven watering.",
 tips:"Bury 2/3 of the transplant stem — it roots along the buried stem. Prune suckers on indeterminates. Water deeply and evenly at the base, never overhead.",
 harvest:"Pick at first blush and finish on the counter; it tastes the same and beats the birds."},
{id:"pepper",n:"Sweet Pepper",e:"🫑",fam:"solanaceae",sun:8,water:1.25,sp:18,psf:0.44,depth:0.25,germ:[7,21],soilF:[70,85,95],dtm:70,from:"transplant",via:3,feeder:"medium",
 start:{indoor:-8,tp:3,fall:null},succ:0,yield:2.5,ph:"6.0–6.8",
 comp:["basil","onion","spinach","tomato","carrot","marigold","nasturtium","oregano"],
 foes:["fennel","kohlrabi","apricot"],
 npk:"Go easy on nitrogen or you get a beautiful leafy plant and three peppers. Epsom salt foliar spray at flowering helps fruit set.",
 tips:"Peppers sulk below 55°F. Pinch the first flower to build a bigger plant. They love bottom heat at germination — a heat mat is the single best upgrade.",
 harvest:"Green is just unripe. Leave them for red/yellow and vitamin C triples."},
{id:"hotpepper",n:"Hot Pepper",e:"🌶️",fam:"solanaceae",sun:8,water:1,sp:18,psf:0.44,depth:0.25,germ:[7,25],soilF:[75,85,95],dtm:80,from:"transplant",via:3,feeder:"medium",
 start:{indoor:-8,tp:3,fall:null},succ:0,yield:1.5,ph:"6.0–6.8",
 comp:["basil","onion","carrot","marigold","nasturtium","oregano","tomato"],foes:["fennel","bean"],
 npk:"Same as sweet peppers. Mild drought stress late in the season actually increases capsaicin — stress them a little for heat.",
 tips:"Hottest varieties want the longest season. Start earliest of anything in your tray.",
 harvest:"Cut with scissors, don't pull — the branches snap."},
{id:"eggplant",n:"Eggplant",e:"🍆",fam:"solanaceae",sun:8,water:1.25,sp:24,psf:0.25,depth:0.25,germ:[7,14],soilF:[75,85,95],dtm:80,from:"transplant",via:4,feeder:"heavy",
 start:{indoor:-8,tp:3,fall:null},succ:0,yield:4,ph:"5.8–6.5",
 comp:["bean","marigold","tarragon","thyme","pepper","spinach"],foes:["fennel"],
 npk:"Balanced 10-10-10 at planting, side-dress at first fruit.",
 tips:"Flea beetles will lace the leaves — row cover until flowering. Needs real heat; black plastic mulch pays off in cool summers.",
 harvest:"Skin should spring back when pressed. Dull skin = overripe and bitter."},
{id:"potato",n:"Potato",e:"🥔",fam:"solanaceae",sun:6,water:1.5,sp:12,psf:1,depth:4,germ:[14,28],soilF:[45,60,75],dtm:90,from:"seed",via:0,feeder:"heavy",
 start:{direct:-2,fall:null},succ:0,yield:5,ph:"5.0–6.0",
 comp:["bean","corn","cabbage","marigold","horseradish","pea","nasturtium"],
 foes:["tomato","cucumber","squash","pumpkin","sunflower","raspberry"],
 npk:"5-10-10. Too much nitrogen = huge tops, marble tubers. Likes acidic soil — skip the lime, it causes scab.",
 tips:"Hill soil up around the stems every few weeks. Any tuber that sees sunlight turns green and mildly toxic — keep them buried.",
 harvest:"New potatoes ~2 weeks after flowering; storage potatoes 2 weeks after the tops die back."},
{id:"tomatillo",n:"Tomatillo",e:"🫒",fam:"solanaceae",sun:8,water:1.25,sp:30,psf:0.2,depth:0.25,germ:[5,10],soilF:[65,80,95],dtm:75,from:"transplant",via:4,feeder:"medium",
 start:{indoor:-6,tp:2,fall:null},succ:0,yield:6,ph:"6.0–7.0",
 comp:["basil","marigold","nasturtium","pepper"],foes:["fennel","corn"],
 npk:"Light feeder compared to tomato — compost is usually enough.",
 tips:"You need at least TWO plants. They are self-incompatible and a single plant sets almost nothing.",
 harvest:"Ready when the husk splits and fills out."},

/* ---------- CUCURBITS ---------- */
{id:"cucumber",n:"Cucumber",e:"🥒",fam:"cucurbit",sun:7,water:1.5,sp:12,psf:1,depth:1,germ:[3,10],soilF:[65,85,95],dtm:58,from:"seed",via:5,feeder:"heavy",
 start:{indoor:-3,tp:2,direct:2,fall:-10},succ:21,yield:8,ph:"6.0–7.0",
 comp:["bean","corn","pea","radish","nasturtium","dill","marigold","sunflower","lettuce"],
 foes:["potato","sage","aromatic-herbs","melon"],
 npk:"Heavy feeder — compost at planting, side-dress with balanced fertilizer when vines run.",
 tips:"Trellis them. Vertical cucumbers are straighter, cleaner, and take 1/4 the space. Bitter fruit = water stress.",
 harvest:"Pick every other day. One oversized cuke tells the plant to stop producing."},
{id:"zucchini",n:"Zucchini / Summer Squash",e:"🥬",fam:"cucurbit",sun:7,water:1.5,sp:24,psf:0.25,depth:1,germ:[5,10],soilF:[65,85,95],dtm:50,from:"seed",via:4,feeder:"heavy",
 start:{indoor:-3,tp:2,direct:2,fall:-9},succ:30,yield:10,ph:"6.0–7.5",
 comp:["corn","bean","nasturtium","marigold","borage","radish","dill"],foes:["potato"],
 npk:"Compost-rich soil; too much N gives leaves and no fruit.",
 tips:"Squash vine borer is the killer — wrap the base of the stem in foil or nylon in early summer. Hand-pollinate at dawn if fruit keeps aborting.",
 harvest:"6–8 inches. Check daily or you'll find a baseball bat."},
{id:"wintersquash",n:"Winter Squash",e:"🎃",fam:"cucurbit",sun:8,water:1.5,sp:36,psf:0.11,depth:1,germ:[5,10],soilF:[65,85,95],dtm:100,from:"seed",via:4,feeder:"heavy",
 start:{indoor:-3,tp:2,direct:2,fall:null},succ:0,yield:15,ph:"6.0–7.0",
 comp:["corn","bean","nasturtium","marigold","borage"],foes:["potato"],
 npk:"Bury compost under the hill. Feed at vining, stop once fruit sizes up.",
 tips:"Give it 6 feet or send it up a strong trellis with slings. Leave one fruit per vine early on to size up the rest.",
 harvest:"Rind should resist a thumbnail. Cure 10 days in the sun, leave 2 inches of stem, and it keeps for months."},
{id:"pumpkin",n:"Pumpkin",e:"🎃",fam:"cucurbit",sun:8,water:1.5,sp:48,psf:0.08,depth:1,germ:[5,10],soilF:[65,85,95],dtm:105,from:"seed",via:4,feeder:"heavy",
 start:{indoor:-2,tp:2,direct:2,fall:null},succ:0,yield:20,ph:"6.0–6.8",
 comp:["corn","bean","nasturtium","marigold","oregano"],foes:["potato"],
 npk:"Very heavy feeder. Compost, then 5-10-10 at flowering.",
 tips:"Count backwards from Halloween: 100–110 days. Slip a board under each fruit to stop rot.",
 harvest:"Hard rind, deep color, dried stem."},
{id:"melon",n:"Cantaloupe / Melon",e:"🍈",fam:"cucurbit",sun:8,water:1.5,sp:24,psf:0.25,depth:1,germ:[4,10],soilF:[70,90,100],dtm:85,from:"seed",via:5,feeder:"heavy",
 start:{indoor:-3,tp:2,direct:2,fall:null},succ:0,yield:8,ph:"6.0–7.0",
 comp:["corn","radish","nasturtium","marigold","borage","sunflower"],foes:["potato","cucumber"],
 npk:"Feed until fruit set, then back off — dry-ish finish concentrates sugar.",
 tips:"Black plastic mulch and a warm site. Cut water back once melons stop sizing.",
 harvest:"Cantaloupe slips from the vine with gentle thumb pressure and smells sweet at the blossom end."},
{id:"watermelon",n:"Watermelon",e:"🍉",fam:"cucurbit",sun:8,water:1.5,sp:36,psf:0.11,depth:1,germ:[4,12],soilF:[70,90,100],dtm:90,from:"seed",via:6,feeder:"heavy",
 start:{indoor:-3,tp:2,direct:2,fall:null},succ:0,yield:20,ph:"6.0–6.8",
 comp:["corn","radish","nasturtium","marigold","borage"],foes:["potato"],
 npk:"Nitrogen early, potassium heavy late.",
 tips:"Needs a long hot run. In short seasons pick a 70-day icebox type.",
 harvest:"Curly tendril nearest the fruit dries brown + ground spot turns buttery yellow + hollow thump."},

/* ---------- LEGUMES ---------- */
{id:"bushbean",n:"Bush Bean",e:"🫘",fam:"legume",sun:6,water:1,sp:4,psf:9,depth:1,germ:[5,10],soilF:[60,80,90],dtm:52,from:"seed",via:3,feeder:"light",
 start:{direct:1,fall:-11},succ:14,yield:0.5,ph:"6.0–7.0",
 comp:["carrot","corn","cucumber","potato","squash","strawberry","celery","radish","marigold","rosemary"],
 foes:["onion","garlic","leek","shallot","chive","fennel","sunflower"],
 npk:"Fixes its own nitrogen — do NOT fertilize with N. Inoculate seed with rhizobia the first year in new ground.",
 tips:"Succession sow every 2 weeks for a steady supply. Don't handle plants when wet — spreads rust and blight.",
 harvest:"Pick before the seeds bulge. Picking daily keeps the plant flowering."},
{id:"polebean",n:"Pole Bean",e:"🌿",fam:"legume",sun:6,water:1,sp:6,psf:8,depth:1,germ:[5,10],soilF:[60,80,90],dtm:65,from:"seed",via:3,feeder:"light",
 start:{direct:1,fall:null},succ:0,yield:1.5,ph:"6.0–7.0",
 comp:["corn","cucumber","radish","carrot","squash","marigold","nasturtium"],
 foes:["onion","garlic","leek","chive","beet","kohlrabi","sunflower"],
 npk:"Nitrogen-fixing. Phosphorus and potassium only.",
 tips:"Three Sisters: corn as the pole, beans feeding the corn, squash shading out weeds. Plant beans two weeks after the corn.",
 harvest:"Pick constantly — one mature pod shuts down flowering."},
{id:"pea",n:"Pea",e:"🫛",fam:"legume",sun:6,water:1,sp:3,psf:8,depth:1,germ:[7,14],soilF:[40,65,80],dtm:60,from:"seed",via:3,feeder:"light",
 start:{direct:-6,fall:-10},succ:14,yield:0.5,ph:"6.0–7.5",
 comp:["carrot","cucumber","corn","radish","turnip","bean","mint","spinach"],
 foes:["onion","garlic","leek","chive","shallot"],
 npk:"No nitrogen. Inoculant helps in new beds.",
 tips:"Peas hate heat — get them in as soon as soil is workable. Soak seed overnight to speed germination.",
 harvest:"Snap peas when pods fill but still snap; shelling peas when round but still bright green."},

/* ---------- BRASSICAS ---------- */
{id:"broccoli",n:"Broccoli",e:"🥦",fam:"brassica",sun:6,water:1.5,sp:18,psf:0.44,depth:0.5,germ:[4,10],soilF:[45,70,85],dtm:65,from:"transplant",via:4,feeder:"heavy",
 start:{indoor:-6,tp:-2,fall:-14},succ:0,yield:1.5,ph:"6.0–7.0",
 comp:["beet","celery","dill","onion","potato","marigold","nasturtium","thyme","rosemary","chamomile","spinach"],
 foes:["tomato","pepper","strawberry","polebean","mustard"],
 npk:"Heavy nitrogen feeder. Side-dress with blood meal or fish emulsion 3 weeks after transplant.",
 tips:"Boron and calcium matter — hollow stems mean boron shortage. Heat makes it bolt; fall crops are usually better than spring.",
 harvest:"Cut the main head while buds are tight, then keep harvesting side shoots for weeks."},
{id:"cauliflower",n:"Cauliflower",e:"🥬",fam:"brassica",sun:6,water:1.5,sp:18,psf:0.44,depth:0.5,germ:[4,10],soilF:[45,70,85],dtm:70,from:"transplant",via:4,feeder:"heavy",
 start:{indoor:-6,tp:-2,fall:-14},succ:0,yield:2,ph:"6.5–7.0",
 comp:["beet","celery","dill","onion","marigold","nasturtium","spinach","thyme"],
 foes:["tomato","strawberry","polebean","pepper"],
 npk:"Steady nitrogen. Any check in growth ruins the head.",
 tips:"The fussiest brassica. Blanch white types by tying outer leaves over the head when it's egg-sized.",
 harvest:"Cut while the curd is tight and smooth — it goes 'ricey' fast in heat."},
{id:"cabbage",n:"Cabbage",e:"🥬",fam:"brassica",sun:6,water:1.5,sp:15,psf:0.44,depth:0.5,germ:[4,10],soilF:[45,70,85],dtm:70,from:"transplant",via:4,feeder:"heavy",
 start:{indoor:-6,tp:-3,fall:-14},succ:0,yield:3,ph:"6.5–7.0",
 comp:["beet","celery","dill","onion","potato","chamomile","marigold","nasturtium","sage","thyme","mint"],
 foes:["tomato","strawberry","polebean","pepper"],
 npk:"Nitrogen at planting and again at heading.",
 tips:"Cabbage worms are inevitable — Bt spray or row cover. Splitting heads mean too much water at maturity; give the plant a quarter turn to break roots.",
 harvest:"Squeeze the head — firm all the way through means ready."},
{id:"kale",n:"Kale",e:"🥬",fam:"brassica",sun:5,water:1.25,sp:15,psf:0.44,depth:0.5,germ:[4,10],soilF:[45,70,85],dtm:55,from:"transplant",via:4,feeder:"medium",
 start:{indoor:-6,tp:-3,direct:-2,fall:-10},succ:0,yield:2,ph:"6.0–7.5",
 comp:["beet","celery","dill","onion","potato","marigold","nasturtium","spinach"],
 foes:["tomato","strawberry","polebean"],
 npk:"Moderate nitrogen; fish emulsion every 3–4 weeks keeps leaves tender.",
 tips:"The most forgiving vegetable there is. Frost genuinely improves the flavor — it converts starch to sugar.",
 harvest:"Pick outer leaves bottom-up and leave the growing tip; one plant produces for months."},
{id:"brussels",n:"Brussels Sprouts",e:"🥬",fam:"brassica",sun:6,water:1.5,sp:24,psf:0.25,depth:0.5,germ:[4,10],soilF:[45,70,85],dtm:100,from:"transplant",via:4,feeder:"heavy",
 start:{indoor:-4,tp:0,fall:-18},succ:0,yield:2,ph:"6.0–7.5",
 comp:["beet","celery","dill","onion","potato","marigold","thyme"],
 foes:["tomato","strawberry","polebean"],
 npk:"Long season, heavy feeder. Side-dress twice.",
 tips:"Top the plant (cut the growing tip) about 4 weeks before harvest to force even sprout sizing. Needs frost to taste right.",
 harvest:"Bottom-up as sprouts firm to about an inch."},
{id:"collards",n:"Collards",e:"🥬",fam:"brassica",sun:5,water:1.25,sp:18,psf:0.44,depth:0.5,germ:[4,10],soilF:[45,70,85],dtm:60,from:"transplant",via:4,feeder:"medium",
 start:{indoor:-6,tp:-3,direct:-2,fall:-12},succ:0,yield:2.5,ph:"6.0–7.5",
 comp:["beet","onion","dill","marigold","nasturtium","potato"],foes:["tomato","strawberry","polebean"],
 npk:"Nitrogen keeps leaves tender.",tips:"Tougher than kale in heat and cold both. A staple crop in the South for a reason.",
 harvest:"Outer leaves continuously; sweeter after frost."},
{id:"kohlrabi",n:"Kohlrabi",e:"🥬",fam:"brassica",sun:6,water:1.25,sp:6,psf:4,depth:0.5,germ:[4,10],soilF:[45,70,85],dtm:55,from:"seed",via:4,feeder:"medium",
 start:{direct:-4,fall:-10},succ:21,yield:0.75,ph:"6.0–7.5",
 comp:["beet","onion","cucumber","dill","marigold"],foes:["tomato","polebean","strawberry","pepper"],
 npk:"Steady moderate feeding; fast growth = tender bulbs.",
 tips:"Grow it fast. Slow-grown kohlrabi is woody.",harvest:"At 2–3 inches. Bigger means fibrous."},
{id:"radish",n:"Radish",e:"🌶️",fam:"brassica",sun:5,water:1,sp:2,psf:16,depth:0.5,germ:[3,7],soilF:[45,65,85],dtm:28,from:"seed",via:5,feeder:"light",
 start:{direct:-4,fall:-6},succ:10,yield:0.1,ph:"6.0–7.0",
 comp:["carrot","cucumber","lettuce","pea","nasturtium","spinach","squash","bean"],foes:["hyssop","grape"],
 npk:"Almost none. Rich soil gives all tops and no root.",
 tips:"The fastest gratification in the garden and a superb row marker for slow seeds like carrots. Hot weather makes them woody and sharp.",
 harvest:"On time — 3–4 weeks. A week late and they split and turn pithy."},
{id:"turnip",n:"Turnip",e:"🥬",fam:"brassica",sun:6,water:1,sp:4,psf:9,depth:0.5,germ:[3,10],soilF:[45,65,85],dtm:50,from:"seed",via:4,feeder:"light",
 start:{direct:-3,fall:-8},succ:21,yield:0.5,ph:"6.0–7.0",
 comp:["pea","radish","onion","mint","nasturtium"],foes:["potato","mustard"],
 npk:"Low nitrogen, phosphorus for root growth.",tips:"Both roots and greens are edible — two crops from one seed.",
 harvest:"2–3 inches across for sweetness."},
{id:"arugula",n:"Arugula",e:"🌿",fam:"brassica",sun:4,water:1,sp:4,psf:9,depth:0.25,germ:[3,7],soilF:[40,60,75],dtm:35,from:"seed",via:4,feeder:"light",
 start:{direct:-5,fall:-6},succ:14,yield:0.2,ph:"6.0–7.0",
 comp:["lettuce","spinach","carrot","onion","bean"],foes:["strawberry"],
 npk:"Light nitrogen only.",tips:"Bolts and turns fiery hot in heat. A pure spring and fall crop.",
 harvest:"Cut-and-come-again at 3 inches; it regrows twice."},
{id:"bokchoy",n:"Bok Choy",e:"🥬",fam:"brassica",sun:5,water:1.25,sp:8,psf:2.25,depth:0.25,germ:[4,8],soilF:[45,65,80],dtm:50,from:"seed",via:4,feeder:"medium",
 start:{direct:-4,fall:-8},succ:21,yield:0.75,ph:"6.0–7.5",
 comp:["beet","onion","dill","nasturtium","marigold"],foes:["tomato","strawberry"],
 npk:"Consistent nitrogen and consistent water.",tips:"Bolts fast if stressed. Baby types are the safer bet in spring.",
 harvest:"Whole head at the base, or outer leaves as you need them."},
{id:"mustard",n:"Mustard Greens",e:"🌿",fam:"brassica",sun:5,water:1,sp:6,psf:4,depth:0.25,germ:[3,7],soilF:[45,65,80],dtm:40,from:"seed",via:4,feeder:"light",
 start:{direct:-4,fall:-7},succ:14,yield:0.4,ph:"6.0–7.5",
 comp:["onion","dill","nasturtium","beet"],foes:["turnip","beet"],
 npk:"Light.",tips:"Doubles as a biofumigant cover crop — chop and till to suppress soil pests.",
 harvest:"Young leaves are mild; older leaves get aggressively spicy."},

/* ---------- GREENS & CHENOPODS ---------- */
{id:"lettuce",n:"Lettuce",e:"🥬",fam:"aster",sun:4,water:1,sp:8,psf:4,depth:0.125,germ:[2,10],soilF:[40,65,75],dtm:50,from:"seed",via:3,feeder:"light",
 start:{indoor:-8,tp:-4,direct:-4,fall:-8},succ:14,yield:0.5,ph:"6.0–7.0",
 comp:["carrot","radish","strawberry","cucumber","onion","beet","chive","marigold"],foes:["broccoli","parsley","celery"],
 npk:"Light steady nitrogen for tender leaves.",
 tips:"Lettuce seed needs light to germinate — press it in, don't bury it. It also refuses to sprout above 80°F soil; sow in the shade of taller crops in summer.",
 harvest:"Cut-and-come-again outer leaves, or the whole head at the base before it gets bitter and bolts."},
{id:"spinach",n:"Spinach",e:"🥬",fam:"chenopod",sun:4,water:1.25,sp:4,psf:9,depth:0.5,germ:[5,14],soilF:[40,60,70],dtm:45,from:"seed",via:3,feeder:"medium",
 start:{direct:-6,fall:-8},succ:14,yield:0.3,ph:"6.5–7.5",
 comp:["strawberry","radish","pea","bean","cabbage","cauliflower","eggplant"],foes:[],
 npk:"Nitrogen-hungry for a green. Fish emulsion every 2–3 weeks.",
 tips:"Bolts the moment days get long — spring spinach is a race. Fall spinach overwinters under mulch in most zones and explodes in March.",
 harvest:"Outer leaves, or cut the whole rosette an inch above the crown."},
{id:"chard",n:"Swiss Chard",e:"🌿",fam:"chenopod",sun:5,water:1.25,sp:9,psf:2.25,depth:0.5,germ:[5,14],soilF:[50,70,85],dtm:55,from:"seed",via:4,feeder:"medium",
 start:{direct:-2,fall:-10},succ:0,yield:2,ph:"6.0–7.5",
 comp:["bean","onion","cabbage","lettuce","mint","marigold"],foes:["corn","cucumber","beet"],
 npk:"Moderate nitrogen every month.",
 tips:"One planting feeds you from June to frost. Each 'seed' is a cluster — thin the seedlings ruthlessly.",
 harvest:"Outer stalks at the base; never take more than a third at once."},
{id:"beet",n:"Beet",e:"🥬",fam:"chenopod",sun:6,water:1,sp:4,psf:9,depth:0.5,germ:[5,14],soilF:[45,70,85],dtm:55,from:"seed",via:4,feeder:"medium",
 start:{direct:-3,fall:-9},succ:21,yield:0.4,ph:"6.0–7.5",
 comp:["bushbean","onion","garlic","lettuce","cabbage","broccoli","kohlrabi","mint"],foes:["polebean","mustard","chard"],
 npk:"Needs boron — deficiency causes black internal spots. Low nitrogen, decent potassium.",
 tips:"Soak seed overnight. Each cluster gives 2–4 plants; thin to one or you get nothing but greens.",
 harvest:"1.5–3 inches. Greens are excellent — harvest a few per plant along the way."},

/* ---------- UMBELLIFERS ---------- */
{id:"carrot",n:"Carrot",e:"🥕",fam:"apiaceae",sun:6,water:1,sp:3,psf:16,depth:0.25,germ:[10,21],soilF:[45,75,85],dtm:70,from:"seed",via:3,feeder:"light",
 start:{direct:-3,fall:-10},succ:21,yield:0.25,ph:"6.0–6.8",
 comp:["tomato","onion","leek","lettuce","pea","radish","rosemary","sage","chive","bean"],
 foes:["dill","fennel","parsnip","celery"],
 npk:"Low nitrogen — high N causes forking and hairy roots. Phosphorus and potassium instead.",
 tips:"The seed is tiny and slow. Keep the surface damp for 3 weeks — a board or burlap over the row is the classic trick. Rocks and clods make forked carrots.",
 harvest:"After a frost for the sweetest roots. Loosen with a fork; don't yank."},
{id:"parsnip",n:"Parsnip",e:"🥕",fam:"apiaceae",sun:6,water:1,sp:4,psf:9,depth:0.5,germ:[14,28],soilF:[45,65,75],dtm:120,from:"seed",via:1,feeder:"light",
 start:{direct:-2,fall:null},succ:0,yield:0.5,ph:"6.0–7.0",
 comp:["radish","pea","lettuce","garlic"],foes:["carrot","celery"],
 npk:"Low nitrogen, deep loose soil.",
 tips:"Use FRESH seed every year — parsnip seed dies in one season. Slow to germinate; be patient.",
 harvest:"Leave in the ground through hard frost. Cold converts starch to sugar and transforms the flavor."},
{id:"celery",n:"Celery",e:"🥬",fam:"apiaceae",sun:6,water:2,sp:8,psf:2.25,depth:0.125,germ:[14,21],soilF:[60,70,75],dtm:100,from:"transplant",via:3,feeder:"heavy",
 start:{indoor:-10,tp:-1,fall:null},succ:0,yield:1.5,ph:"6.0–7.0",
 comp:["bean","cabbage","broccoli","leek","onion","spinach","tomato"],foes:["carrot","parsnip","corn"],
 npk:"Constant nitrogen and constant water — the thirstiest thing in the garden.",
 tips:"Never let it dry out for a day. Dry celery is stringy and bitter. Blanch stalks with a collar for 2 weeks before harvest.",
 harvest:"Outer stalks as needed, or the whole plant at the base."},
{id:"cilantro",n:"Cilantro",e:"🌿",fam:"apiaceae",sun:5,water:1,sp:6,psf:4,depth:0.5,germ:[7,14],soilF:[50,65,75],dtm:45,from:"seed",via:3,feeder:"light",
 start:{direct:-3,fall:-8},succ:14,yield:0.2,ph:"6.2–6.8",
 comp:["spinach","potato","cabbage","tomato","anise"],foes:["fennel"],
 npk:"Minimal.",tips:"Bolts in heat, full stop. Sow every 2 weeks in spring and fall and accept it. The bolted seed is coriander — don't waste it.",
 harvest:"Outer leaves; cut the whole plant once it starts to send up a flower stalk."},
{id:"dill",n:"Dill",e:"🌿",fam:"apiaceae",sun:6,water:1,sp:8,psf:2.25,depth:0.25,germ:[7,21],soilF:[60,70,75],dtm:45,from:"seed",via:3,feeder:"light",
 start:{direct:0,fall:-9},succ:21,yield:0.2,ph:"5.5–6.5",
 comp:["cabbage","broccoli","cucumber","lettuce","onion","corn","asparagus"],
 foes:["carrot","tomato","fennel","lavender"],
 npk:"None needed.",tips:"Magnet for beneficial wasps and swallowtail caterpillars. Self-sows forever once established. Keep it away from mature tomatoes.",
 harvest:"Leaves anytime; seed heads when they turn tan."},
{id:"parsley",n:"Parsley",e:"🌿",fam:"apiaceae",sun:5,water:1,sp:8,psf:2.25,depth:0.25,germ:[14,28],soilF:[50,70,85],dtm:75,from:"transplant",via:2,feeder:"medium",
 start:{indoor:-8,tp:-2,direct:-2,fall:-10},succ:0,yield:0.5,ph:"6.0–7.0",
 comp:["tomato","asparagus","corn","pepper","carrot","chive","rose"],foes:["lettuce","mint"],
 npk:"Light nitrogen every 6 weeks.",tips:"Notoriously slow to sprout — soak seed overnight. Biennial: it flowers and dies in year two.",
 harvest:"Outer stems at the base; it regrows from the center all season."},
{id:"fennel",n:"Fennel",e:"🌿",fam:"apiaceae",sun:6,water:1,sp:12,psf:1,depth:0.25,germ:[7,14],soilF:[60,70,80],dtm:80,from:"seed",via:3,feeder:"medium",
 start:{direct:-2,fall:-12},succ:0,yield:1,ph:"6.0–7.0",
 comp:[],foes:["tomato","bushbean","polebean","pepper","dill","cilantro","carrot","kohlrabi","caraway"],
 npk:"Moderate; hill soil around the bulb.",
 tips:"Fennel is the garden's antisocial neighbor — it inhibits most vegetables. Give it its own corner or a pot.",
 harvest:"Bulb at tennis-ball size, before it bolts."},

/* ---------- ALLIUMS ---------- */
{id:"onion",n:"Onion",e:"🧅",fam:"allium",sun:6,water:1,sp:4,psf:9,depth:0.5,germ:[7,14],soilF:[50,70,85],dtm:110,from:"transplant",via:1,feeder:"medium",
 start:{indoor:-12,tp:-4,direct:-4,fall:null},succ:0,yield:0.5,ph:"6.0–7.0",
 comp:["carrot","beet","lettuce","strawberry","tomato","cabbage","broccoli","chard","chamomile"],
 foes:["bushbean","polebean","pea","asparagus","sage"],
 npk:"Nitrogen early for big tops (tops make bulb size), then stop at bulbing.",
 tips:"Day length decides bulb size — long-day onions north of 36°N, short-day south, intermediate in between. Planting the wrong type is the #1 onion failure. Onion seed dies in a year; buy fresh.",
 harvest:"When half the tops flop, stop watering, then lift and cure 2–3 weeks in shade."},
{id:"garlic",n:"Garlic",e:"🧄",fam:"allium",sun:6,water:0.75,sp:6,psf:4,depth:2,germ:[14,28],soilF:[40,60,75],dtm:240,from:"seed",via:0,feeder:"medium",
 start:{fallPlant:-3,fall:-3},succ:0,yield:0.3,ph:"6.0–7.0",
 comp:["tomato","carrot","beet","strawberry","cabbage","fruit-trees","rose"],
 foes:["bushbean","polebean","pea","asparagus"],
 npk:"Nitrogen in early spring when leaves push, none after mid-May.",
 tips:"Plant cloves 2–3 weeks before your first fall frost, pointy end up, mulch heavily. Snap off hardneck scapes in June — bulbs get 25% bigger, and the scapes are delicious.",
 harvest:"When the bottom 3–4 leaves brown. Cure 3 weeks before trimming."},
{id:"leek",n:"Leek",e:"🧅",fam:"allium",sun:6,water:1.25,sp:6,psf:4,depth:0.5,germ:[10,14],soilF:[50,70,85],dtm:120,from:"transplant",via:2,feeder:"heavy",
 start:{indoor:-12,tp:-3,fall:null},succ:0,yield:0.5,ph:"6.0–7.0",
 comp:["carrot","celery","onion","strawberry","tomato"],foes:["bean","pea"],
 npk:"Steady nitrogen all season.",
 tips:"Drop transplants into 6-inch dibbled holes and just water them in — the hole self-fills and blanches a long white shank.",
 harvest:"Anytime after pencil thickness; extremely frost hardy."},
{id:"shallot",n:"Shallot",e:"🧅",fam:"allium",sun:6,water:1,sp:6,psf:4,depth:1,germ:[10,20],soilF:[45,65,80],dtm:100,from:"seed",via:1,feeder:"medium",
 start:{direct:-4,fallPlant:-4,fall:-4},succ:0,yield:0.4,ph:"6.0–7.0",
 comp:["carrot","beet","lettuce","strawberry","tomato"],foes:["bean","pea"],
 npk:"Same as onion.",tips:"Each bulb multiplies into a clump of 6–10. Save your best for replanting.",
 harvest:"When tops yellow; cure like onions."},
{id:"chive",n:"Chives",e:"🌿",fam:"allium",sun:5,water:1,sp:6,psf:4,depth:0.25,germ:[10,21],soilF:[60,70,80],dtm:80,from:"transplant",via:1,feeder:"light",
 start:{indoor:-8,tp:-2,direct:-2,fall:null},succ:0,yield:0.3,ph:"6.0–7.0",
 comp:["carrot","tomato","rose","grape","lettuce","strawberry"],foes:["bean","pea"],
 npk:"Compost once a year.",tips:"Perennial — plant once, divide every 3 years. The purple flowers are edible and repel aphids.",
 harvest:"Cut to 2 inches; it regrows in a couple of weeks."},

/* ---------- OTHERS ---------- */
{id:"corn",n:"Sweet Corn",e:"🌽",fam:"poaceae",sun:8,water:1.5,sp:12,psf:1,depth:1.5,germ:[5,12],soilF:[60,75,95],dtm:80,from:"seed",via:2,feeder:"heavy",
 start:{direct:2,fall:null},succ:14,yield:1.5,ph:"6.0–6.8",
 comp:["bean","cucumber","melon","pea","potato","pumpkin","squash","sunflower","dill"],
 foes:["tomato","celery"],
 npk:"Very heavy nitrogen. Side-dress at knee-high and again at tasseling.",
 tips:"Plant in a block of at least 4x4, never a single long row — corn is wind-pollinated and a row gives you gap-toothed ears. Keep varieties 25 feet apart or they cross.",
 harvest:"Silks brown and dry, kernels squirt milky juice. Sugar starts converting to starch within hours — pick and cook the same day."},
{id:"okra",n:"Okra",e:"🌿",fam:"malvaceae",sun:8,water:1,sp:15,psf:0.44,depth:0.75,germ:[7,14],soilF:[70,85,95],dtm:55,from:"seed",via:2,feeder:"medium",
 start:{direct:2,indoor:-2,tp:3,fall:null},succ:0,yield:2,ph:"6.5–7.0",
 comp:["pepper","basil","melon","lettuce","cucumber","sweetpotato"],foes:[],
 npk:"Balanced; too much N delays pods.",
 tips:"Loves brutal heat. Soak seed 12 hours. Wear sleeves — the pods and leaves irritate skin.",
 harvest:"Every single day at 3 inches. A 5-inch pod is a woodchip."},
{id:"sweetpotato",n:"Sweet Potato",e:"🍠",fam:"convolvulaceae",sun:8,water:1,sp:12,psf:1,depth:4,germ:[14,21],soilF:[65,80,95],dtm:100,from:"transplant",via:0,feeder:"light",
 start:{tp:3,fall:null},succ:0,yield:3,ph:"5.5–6.5",
 comp:["bean","beet","dill","thyme","okra"],foes:["squash","pumpkin"],
 npk:"Low nitrogen — high N gives vines and no roots. Potassium is what you want.",
 tips:"Grown from slips, not seed. Needs warm soil, 65°F+. Loose sandy soil or a deep raised bed.",
 harvest:"Before the first frost hits the vines. Cure at 80°F and high humidity for 10 days — this is what makes them sweet."},
{id:"strawberry",n:"Strawberry",e:"🍓",fam:"rosaceae",sun:7,water:1.25,sp:12,psf:1,depth:0,germ:[14,28],soilF:[50,65,80],dtm:365,from:"transplant",via:0,feeder:"medium",
 start:{tp:-2,fall:null},succ:0,yield:1,ph:"5.5–6.5",
 comp:["bean","borage","lettuce","spinach","onion","thyme","marigold"],
 foes:["cabbage","broccoli","cauliflower","kale","brussels","fennel","tomato"],
 npk:"Balanced after fruiting, not before — spring nitrogen gives soft fruit and rot.",
 tips:"Pinch every flower the first year on June-bearers; you trade one small crop for three big ones. Renovate the bed after fruiting.",
 harvest:"Fully red, in the morning while cool. They don't ripen further off the plant."},
{id:"asparagus",n:"Asparagus",e:"🌿",fam:"asparagaceae",sun:7,water:1,sp:18,psf:0.44,depth:6,germ:[14,28],soilF:[50,75,85],dtm:730,from:"transplant",via:3,feeder:"heavy",
 start:{tp:-2,fall:null},succ:0,yield:0.5,ph:"6.5–7.5",
 comp:["tomato","basil","parsley","marigold","dill","strawberry"],foes:["onion","garlic","potato"],
 npk:"Heavy compost in spring and again after the harvest window closes.",
 tips:"A 20-year investment. Do not harvest at all in year one, lightly in year two, fully in year three. Site it where you'll never till.",
 harvest:"Snap spears at 7–9 inches for about 6 weeks, then let the ferns feed the crown."},
{id:"rhubarb",n:"Rhubarb",e:"🌿",fam:"polygonaceae",sun:6,water:1.25,sp:36,psf:0.11,depth:2,germ:[10,21],soilF:[50,70,80],dtm:730,from:"transplant",via:2,feeder:"heavy",
 start:{tp:-4,fall:null},succ:0,yield:3,ph:"6.0–6.8",
 comp:["cabbage","broccoli","garlic","onion","strawberry"],foes:[],
 npk:"Heavy compost annually; it's a permanent bed.",
 tips:"Leaves are toxic (oxalic acid) — stalks only. Remove flower stalks the moment they appear. Needs winter cold, so it struggles below zone 6.",
 harvest:"Twist and pull stalks; never take more than a third. None in year one."},

/* ---------- HERBS & FLOWERS ---------- */
{id:"basil",n:"Basil",e:"🌿",fam:"lamiaceae",sun:6,water:1,sp:10,psf:2.25,depth:0.25,germ:[5,10],soilF:[65,75,85],dtm:60,from:"transplant",via:5,feeder:"light",
 start:{indoor:-6,tp:2,direct:2,fall:null},succ:21,yield:0.5,ph:"6.0–7.5",
 comp:["tomato","pepper","oregano","asparagus","marigold","eggplant","petunia"],foes:["rue","sage","cucumber"],
 npk:"Light. Excess nitrogen kills the aroma.",
 tips:"Pinch above a leaf pair every couple of weeks and it doubles; let it flower and it's over. Cold below 50°F blackens the leaves.",
 harvest:"Whole stems above a node, morning, before the sun burns off the oils."},
{id:"oregano",n:"Oregano",e:"🌿",fam:"lamiaceae",sun:6,water:0.5,sp:12,psf:1,depth:0.125,germ:[7,14],soilF:[60,70,80],dtm:80,from:"transplant",via:4,feeder:"light",
 start:{indoor:-8,tp:0,fall:null},succ:0,yield:0.4,ph:"6.0–8.0",
 comp:["tomato","pepper","cabbage","broccoli","cucumber","bean","grape"],foes:[],
 npk:"None. Poor soil makes stronger flavor.",tips:"Perennial in zones 5+. Drought-loving — overwatering is the usual killer.",
 harvest:"Just before flowering, when the oils peak."},
{id:"thyme",n:"Thyme",e:"🌿",fam:"lamiaceae",sun:6,water:0.5,sp:12,psf:1,depth:0.125,germ:[14,28],soilF:[60,70,80],dtm:90,from:"transplant",via:3,feeder:"light",
 start:{indoor:-8,tp:0,fall:null},succ:0,yield:0.25,ph:"6.0–8.0",
 comp:["cabbage","broccoli","strawberry","tomato","eggplant","potato","rose"],foes:[],
 npk:"None.",tips:"Repels cabbage worms. Needs sharp drainage — it drowns in rich wet beds.",
 harvest:"Cut sprigs anytime; trim hard in spring to prevent woodiness."},
{id:"rosemary",n:"Rosemary",e:"🌿",fam:"lamiaceae",sun:7,water:0.5,sp:24,psf:0.25,depth:0.125,germ:[14,30],soilF:[65,75,85],dtm:120,from:"transplant",via:2,feeder:"light",
 start:{indoor:-10,tp:1,fall:null},succ:0,yield:0.5,ph:"6.0–7.5",
 comp:["cabbage","bean","carrot","sage","broccoli"],foes:["cucumber","basil","tomato"],
 npk:"None.",tips:"Hardy only to about zone 7 — pot it and bring it in north of that. Notoriously slow from seed; take cuttings instead.",
 harvest:"Sprigs year-round; never take more than 20% at once."},
{id:"sage",n:"Sage",e:"🌿",fam:"lamiaceae",sun:6,water:0.5,sp:18,psf:0.44,depth:0.25,germ:[10,21],soilF:[60,70,80],dtm:90,from:"transplant",via:3,feeder:"light",
 start:{indoor:-8,tp:0,fall:null},succ:0,yield:0.4,ph:"6.0–7.0",
 comp:["cabbage","broccoli","carrot","rosemary","strawberry","tomato"],foes:["cucumber","onion","basil"],
 npk:"None.",tips:"Repels cabbage moths. Replace plants every 4–5 years as they go woody.",
 harvest:"Leaves before flowering; light harvest in year one."},
{id:"mint",n:"Mint",e:"🌿",fam:"lamiaceae",sun:4,water:1.5,sp:18,psf:0.44,depth:0.25,germ:[10,15],soilF:[60,70,80],dtm:90,from:"transplant",via:2,feeder:"light",
 start:{indoor:-8,tp:0,fall:null},succ:0,yield:1,ph:"6.0–7.5",
 comp:["cabbage","broccoli","tomato","pea","turnip"],foes:["parsley","chamomile"],
 npk:"Minimal.",tips:"Plant it in a buried pot or it will own your entire bed within two seasons. This is not an exaggeration.",
 harvest:"Cut stems back by half; it comes right back."},
{id:"marigold",n:"Marigold",e:"🌼",fam:"aster",sun:6,water:0.75,sp:10,psf:2.25,depth:0.25,germ:[5,10],soilF:[65,75,85],dtm:50,from:"seed",via:2,feeder:"light",
 start:{indoor:-6,tp:1,direct:1,fall:null},succ:0,yield:0,ph:"6.0–7.5",
 comp:["tomato","pepper","cucumber","squash","bean","potato","broccoli","cabbage","melon","eggplant"],foes:[],
 npk:"None — poor soil gives more flowers.",
 tips:"French marigolds genuinely suppress root-knot nematodes when grown as a dense planting. They also pull thrips and slugs away from your crops.",
 harvest:"Deadhead constantly for continuous bloom."},
{id:"nasturtium",n:"Nasturtium",e:"🌺",fam:"tropaeolaceae",sun:5,water:0.75,sp:12,psf:1,depth:1,germ:[7,12],soilF:[55,65,75],dtm:50,from:"seed",via:5,feeder:"light",
 start:{direct:1,fall:null},succ:0,yield:0,ph:"6.0–7.5",
 comp:["cucumber","squash","tomato","radish","cabbage","broccoli","bean","melon","potato"],foes:[],
 npk:"None. Rich soil gives all leaves, no flowers.",
 tips:"The best trap crop there is — aphids and cabbage whites go to it instead of your brassicas. Leaves and flowers are peppery and edible.",
 harvest:"Flowers and young leaves for salads; green seed pods pickle like capers."},
{id:"sunflower",n:"Sunflower",e:"🌻",fam:"aster",sun:8,water:1,sp:18,psf:0.44,depth:1,germ:[7,14],soilF:[60,75,85],dtm:90,from:"seed",via:3,feeder:"medium",
 start:{direct:1,fall:null},succ:14,yield:0.5,ph:"6.0–7.5",
 comp:["cucumber","corn","melon","squash"],foes:["potato","polebean"],
 npk:"Moderate; deep roots find their own.",
 tips:"Mildly allelopathic — the roots and hulls suppress nearby seedlings, especially beans and potatoes. Plant on the north side so it doesn't shade everything.",
 harvest:"Back of the head turns yellow-brown; cover with mesh or the birds get all of it."},
{id:"borage",n:"Borage",e:"🌸",fam:"boraginaceae",sun:6,water:0.75,sp:18,psf:0.44,depth:0.5,germ:[5,15],soilF:[60,70,80],dtm:55,from:"seed",via:3,feeder:"light",
 start:{direct:0,fall:null},succ:0,yield:0,ph:"6.0–7.5",
 comp:["tomato","squash","strawberry","cucumber","cabbage","pumpkin"],foes:[],
 npk:"None.",tips:"Best bee magnet you can plant — measurably increases fruit set on tomatoes and squash. Accumulates minerals; chop it into the compost.",
 harvest:"Blue star flowers taste of cucumber. Self-sows generously."},
{id:"calendula",n:"Calendula",e:"🌼",fam:"aster",sun:5,water:0.75,sp:12,psf:1,depth:0.25,germ:[7,14],soilF:[55,70,80],dtm:50,from:"seed",via:2,feeder:"light",
 start:{direct:-2,fall:-8},succ:0,yield:0,ph:"6.0–7.0",
 comp:["tomato","asparagus","carrot","lettuce","brassicas"],foes:[],
 npk:"None.",tips:"Trap crop for aphids and a host plant for hoverflies, whose larvae eat aphids by the hundred. Blooms through frost.",
 harvest:"Petals for salads and salves; deadhead to keep it going."}
];

const CROP = {};
CROPS.forEach(c => CROP[c.id] = c);
function crop(id){ return CROP[id] || null; }
function cropName(id){ const c = CROP[id]; return c ? c.n : (id || "—"); }
function cropEmoji(id){ const c = CROP[id]; return c ? c.e : "🌱"; }

/* ---------- companion logic ---------- */
function pairRating(aId, bId){
  const a = CROP[aId], b = CROP[bId];
  if(!a || !b) return { score: 0, label: "unknown", why: "" };
  if(aId === bId) return { score: 0, label: "same", why: "Same crop" };
  const aFoe = (a.foes || []).indexOf(bId) >= 0, bFoe = (b.foes || []).indexOf(aId) >= 0;
  const aFam = (a.foes || []).indexOf(b.fam) >= 0;
  if(aFoe || bFoe || aFam) return { score: -2, label: "avoid", why: a.n + " and " + b.n + " compete or share pests/diseases." };
  const aC = (a.comp || []).indexOf(bId) >= 0, bC = (b.comp || []).indexOf(aId) >= 0;
  if(aC && bC) return { score: 2, label: "great", why: "Classic companions — both sides benefit." };
  if(aC || bC) return { score: 1, label: "good", why: (aC ? b.n + " helps " + a.n : a.n + " helps " + b.n) + "." };
  if(a.fam === b.fam) return { score: -1, label: "caution", why: "Same family (" + FAMILY[a.fam].n + ") — shares pests and depletes the same nutrients. Fine together, but rotate them as a group." };
  return { score: 0, label: "neutral", why: "No known interaction — safe to plant together." };
}
function companionsFor(id){
  const c = CROP[id]; if(!c) return { good: [], bad: [] };
  const good = (c.comp || []).filter(x => CROP[x]);
  CROPS.forEach(o => { if(o.id !== id && (o.comp || []).indexOf(id) >= 0 && good.indexOf(o.id) < 0) good.push(o.id); });
  const bad = (c.foes || []).filter(x => CROP[x]);
  CROPS.forEach(o => { if(o.id !== id && (o.foes || []).indexOf(id) >= 0 && bad.indexOf(o.id) < 0) bad.push(o.id); });
  return { good: good, bad: bad };
}
</script>
